/*
 * This file is generated by jOOQ.
 */
package net.testproj.db.pb.tables.records;


import java.util.UUID;

import net.testproj.db.pb.tables.Products;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductsRecord extends UpdatableRecordImpl<ProductsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.products.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.products.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.products.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.products.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.products.price</code>.
     */
    public void setPrice(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.products.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.products.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.products.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.products.categories</code>.
     */
    public void setCategories(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.products.categories</code>.
     */
    public String getCategories() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.products.rating</code>.
     */
    public void setRating(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.products.rating</code>.
     */
    public Integer getRating() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductsRecord
     */
    public ProductsRecord() {
        super(Products.PRODUCTS);
    }

    /**
     * Create a detached, initialised ProductsRecord
     */
    public ProductsRecord(UUID id, String title, Integer price, String description, String categories, Integer rating) {
        super(Products.PRODUCTS);

        setId(id);
        setTitle(title);
        setPrice(price);
        setDescription(description);
        setCategories(categories);
        setRating(rating);
        resetChangedOnNotNull();
    }
}
