/*
 * This file is generated by jOOQ.
 */
package net.testproj.db.auth.schema.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import net.testproj.db.auth.schema.tables.AuthUsers;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuthUsersRecord extends UpdatableRecordImpl<AuthUsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>auth.auth_users.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>auth.auth_users.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>auth.auth_users.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>auth.auth_users.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>auth.auth_users.updated</code>.
     */
    public void setUpdated(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>auth.auth_users.updated</code>.
     */
    public LocalDateTime getUpdated() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>auth.auth_users.disabled</code>.
     */
    public void setDisabled(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>auth.auth_users.disabled</code>.
     */
    public Boolean getDisabled() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>auth.auth_users.activated</code>.
     */
    public void setActivated(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>auth.auth_users.activated</code>.
     */
    public Boolean getActivated() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>auth.auth_users.role</code>.
     */
    public void setRole(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>auth.auth_users.role</code>.
     */
    public Integer getRole() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>auth.auth_users.login</code>.
     */
    public void setLogin(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>auth.auth_users.login</code>.
     */
    public String getLogin() {
        return (String) get(6);
    }

    /**
     * Setter for <code>auth.auth_users.password</code>.
     */
    public void setPassword(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>auth.auth_users.password</code>.
     */
    public String getPassword() {
        return (String) get(7);
    }

    /**
     * Setter for <code>auth.auth_users.email</code>.
     */
    public void setEmail(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>auth.auth_users.email</code>.
     */
    public String getEmail() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthUsersRecord
     */
    public AuthUsersRecord() {
        super(AuthUsers.AUTH_USERS);
    }

    /**
     * Create a detached, initialised AuthUsersRecord
     */
    public AuthUsersRecord(UUID id, LocalDateTime created, LocalDateTime updated, Boolean disabled, Boolean activated, Integer role, String login, String password, String email) {
        super(AuthUsers.AUTH_USERS);

        setId(id);
        setCreated(created);
        setUpdated(updated);
        setDisabled(disabled);
        setActivated(activated);
        setRole(role);
        setLogin(login);
        setPassword(password);
        setEmail(email);
        resetChangedOnNotNull();
    }
}
