/*
 * This file is generated by jOOQ.
 */
package net.testproj.db.auth.schema.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import net.testproj.db.auth.schema.enums.ConfirmationTokenStatus;
import net.testproj.db.auth.schema.tables.EmailConfirmationTokens;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmailConfirmationTokensRecord extends UpdatableRecordImpl<EmailConfirmationTokensRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>auth.email_confirmation_tokens.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>auth.email_confirmation_tokens.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>auth.email_confirmation_tokens.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>auth.email_confirmation_tokens.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>auth.email_confirmation_tokens.token</code>.
     */
    public void setToken(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>auth.email_confirmation_tokens.token</code>.
     */
    public UUID getToken() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>auth.email_confirmation_tokens.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>auth.email_confirmation_tokens.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>auth.email_confirmation_tokens.expires_at</code>.
     */
    public void setExpiresAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>auth.email_confirmation_tokens.expires_at</code>.
     */
    public LocalDateTime getExpiresAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>auth.email_confirmation_tokens.status</code>.
     */
    public void setStatus(ConfirmationTokenStatus value) {
        set(5, value);
    }

    /**
     * Getter for <code>auth.email_confirmation_tokens.status</code>.
     */
    public ConfirmationTokenStatus getStatus() {
        return (ConfirmationTokenStatus) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmailConfirmationTokensRecord
     */
    public EmailConfirmationTokensRecord() {
        super(EmailConfirmationTokens.EMAIL_CONFIRMATION_TOKENS);
    }

    /**
     * Create a detached, initialised EmailConfirmationTokensRecord
     */
    public EmailConfirmationTokensRecord(UUID id, UUID userId, UUID token, LocalDateTime createdAt, LocalDateTime expiresAt, ConfirmationTokenStatus status) {
        super(EmailConfirmationTokens.EMAIL_CONFIRMATION_TOKENS);

        setId(id);
        setUserId(userId);
        setToken(token);
        setCreatedAt(createdAt);
        setExpiresAt(expiresAt);
        setStatus(status);
        resetChangedOnNotNull();
    }
}
