/*
 * This file is generated by jOOQ.
 */
package net.testproj.db.pb.schema.tables.records;


import net.testproj.db.pb.schema.tables.Product;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.product.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.product.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.product.categories</code>.
     */
    public void setCategories(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.product.categories</code>.
     */
    public String getCategories() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.product.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.product.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.product.price</code>.
     */
    public void setPrice(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.product.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.product.rating</code>.
     */
    public void setRating(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.product.rating</code>.
     */
    public Integer getRating() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.product.title</code>.
     */
    public void setTitle(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.product.title</code>.
     */
    public String getTitle() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(Product.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(Integer id, String categories, String description, Integer price, Integer rating, String title) {
        super(Product.PRODUCT);

        setId(id);
        setCategories(categories);
        setDescription(description);
        setPrice(price);
        setRating(rating);
        setTitle(title);
        resetChangedOnNotNull();
    }
}
