/*
 * This file is generated by jOOQ.
 */
package net.testproj.db.pb.schema.tables.records;


import net.testproj.db.pb.schema.tables.Review;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReviewRecord extends UpdatableRecordImpl<ReviewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.review.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.review.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.review.comment</code>.
     */
    public void setComment(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.review.comment</code>.
     */
    public String getComment() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.review.product_id</code>.
     */
    public void setProductId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.review.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.review.rating</code>.
     */
    public void setRating(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.review.rating</code>.
     */
    public Integer getRating() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.review.timestamp</code>.
     */
    public void setTimestamp(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.review.timestamp</code>.
     */
    public String getTimestamp() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.review.user_name</code>.
     */
    public void setUserName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.review.user_name</code>.
     */
    public String getUserName() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReviewRecord
     */
    public ReviewRecord() {
        super(Review.REVIEW);
    }

    /**
     * Create a detached, initialised ReviewRecord
     */
    public ReviewRecord(Integer id, String comment, Integer productId, Integer rating, String timestamp, String userName) {
        super(Review.REVIEW);

        setId(id);
        setComment(comment);
        setProductId(productId);
        setRating(rating);
        setTimestamp(timestamp);
        setUserName(userName);
        resetChangedOnNotNull();
    }
}
