/*
 * This file is generated by jOOQ.
 */
package net.testproj.db.pb.schema.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import net.testproj.db.pb.schema.tables.Users;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.users.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.users.nick_name</code>.
     */
    public void setNickName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.users.nick_name</code>.
     */
    public String getNickName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.users.day_of_birth</code>.
     */
    public void setDayOfBirth(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.users.day_of_birth</code>.
     */
    public LocalDateTime getDayOfBirth() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.users.auth_user_id</code>.
     */
    public void setAuthUserId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.users.auth_user_id</code>.
     */
    public UUID getAuthUserId() {
        return (UUID) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(UUID id, String nickName, LocalDateTime dayOfBirth, UUID authUserId) {
        super(Users.USERS);

        setId(id);
        setNickName(nickName);
        setDayOfBirth(dayOfBirth);
        setAuthUserId(authUserId);
        resetChangedOnNotNull();
    }
}
