/*
 * This file is generated by jOOQ.
 */
package net.testproj.db.auth.schema.enums;


import net.testproj.db.auth.schema.Auth;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum ConfirmationTokenStatus implements EnumType {

    PENDING("PENDING"),

    CONFIRMED("CONFIRMED"),

    EXPIRED("EXPIRED");

    private final String literal;

    private ConfirmationTokenStatus(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Auth.AUTH;
    }

    @Override
    public String getName() {
        return "confirmation_token_status";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static ConfirmationTokenStatus lookupLiteral(String literal) {
        return EnumType.lookupLiteral(ConfirmationTokenStatus.class, literal);
    }
}
