spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true
      mail.debug: true
  flyway:
    enabled: false
  datasource:
    auth:
      url: jdbc:postgresql://testproj-flex-dev.postgres.database.azure.com:5432/postgres
      username: adm
      password: 24o62o!!
      driver-class-name: org.postgresql.Driver
      schema: auth
      platform: postgres
    public:
      url: jdbc:postgresql://testproj-flex-dev.postgres.database.azure.com:5432/postgres
      username: adm
      password: 24o62o!!
      driver-class-name: org.postgresql.Driver
      schema: public
      platform: postgres
logging:
  level:
    org.flywaydb: DEBUG
