spring:
  flyway:
    enabled: false
  datasource:
      url: ${DB_URL}
      username: ${DB_USER_NAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, email, profile
        provider:
          google:
            issuer-uri: https://accounts.google.com
logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
api:
  security:
    jwt:
      truststore:
        location: classpath:keys/dev-truststore.p12
        store-password: ${JWT_TRUSTSTORE_PASSWORD}
        type: PKCS12
        alias: dev-cert
      issuer: "testproj-auth"
      audience: "testproj-api"
auth:
  security:
    jwt:
      keystore:
        type: PKCS12
        location: classpath:keys/dev-keystore.p12
        store-password: ${JWT_KEYSTORE_PASSWORD}
        key-alias: dev-keypair
        key-password: ${JWT_KEY_PASSWORD}