<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.testproj.db</groupId>
        <artifactId>db</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>ds</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.f4b6a3</groupId>
            <artifactId>uuid-creator</artifactId>
        </dependency>
        <dependency>
            <groupId>net.testproj.db</groupId>
            <artifactId>schema</artifactId>
        </dependency>
        <dependency>
            <groupId>net.testproj.db</groupId>
            <artifactId>model</artifactId>
        </dependency>
    </dependencies>
</project>
