/*
 * This file is generated by jOOQ.
 */
package net.testproj.db.pb.schema;


import net.testproj.db.pb.schema.tables.FlywaySchemaHistory;
import net.testproj.db.pb.schema.tables.Product;
import net.testproj.db.pb.schema.tables.Review;
import net.testproj.db.pb.schema.tables.Users;
import net.testproj.db.pb.schema.tables.records.FlywaySchemaHistoryRecord;
import net.testproj.db.pb.schema.tables.records.ProductRecord;
import net.testproj.db.pb.schema.tables.records.ReviewRecord;
import net.testproj.db.pb.schema.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<ProductRecord> PRODUCT_PKEY = Internal.createUniqueKey(Product.PRODUCT, DSL.name("product_pkey"), new TableField[] { Product.PRODUCT.ID }, true);
    public static final UniqueKey<ReviewRecord> REVIEW_PKEY = Internal.createUniqueKey(Review.REVIEW, DSL.name("review_pkey"), new TableField[] { Review.REVIEW.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_AUTH_USER_ID_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_auth_user_id_key"), new TableField[] { Users.USERS.AUTH_USER_ID }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ReviewRecord, ProductRecord> REVIEW__FK_DEVICE_ATTESTATIONS_DEVICES = Internal.createForeignKey(Review.REVIEW, DSL.name("fk_device_attestations_devices"), new TableField[] { Review.REVIEW.PRODUCT_ID }, Keys.PRODUCT_PKEY, new TableField[] { Product.PRODUCT.ID }, true);
}
