/*
 * This file is generated by jOOQ.
 */
package net.testproj.db.pb.schema;


import net.testproj.db.pb.schema.tables.FlywaySchemaHistory;
import net.testproj.db.pb.schema.tables.Product;
import net.testproj.db.pb.schema.tables.Review;
import net.testproj.db.pb.schema.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.product</code>.
     */
    public static final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>public.review</code>.
     */
    public static final Review REVIEW = Review.REVIEW;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
