flyway.url=jdbc:postgresql://localhost:5432/postgres
flyway.password=24o62o!!
flyway.user=adm
flyway.createSchemas=true
flyway.schemas=auth
flyway.defaultSchema=auth
flyway.driver=org.postgresql.Driver
flyway.locations=classpath:db/migration/auth_migration