flyway.url=jdbc:postgresql://auction4.postgres.database.azure.com:5432/postgres?currentSchema=auth
flyway.password=24o62o!!
flyway.user=adm
flyway.schemas=auth
flyway.driver=org.postgresql.Driver
flyway.locations=filesystem:C:\server\db\schema\src\main\resources\db\migration\auth_migration