flyway.url=jdbc:postgresql://localhost:5432/postgres
flyway.password=24o62o!!
flyway.user=adm
flyway.schemas=public
flyway.defaultSchema=public
flyway.createSchemas=true
flyway.driver=org.postgresql.Driver
flyway.locations=classpath:db/migration/public_migration