flyway.url=jdbc:postgresql://auction4.postgres.database.azure.com:5432/postgres
flyway.password=24o62o!!
flyway.user=adm
flyway.schemas=public
flyway.driver=org.postgresql.Driver
flyway.locations=classpath:db/migration
flyway.baselineOnMigrate=true
flyway.sslMode=verify-full
flyway.sslRootCert=classpath:certs/azure-ca.pem


flyway.outputQueryResults=true
flyway.cleanOnValidationError=true
flyway.validateOnMigrate=true
flyway.mixed=true
flyway.debug=true