flyway.url=${DB_URL}
flyway.password=${DB_PASSWORD}
flyway.user= ${DB_USER_NAME}
flyway.createSchemas=true
flyway.schemas=auth
flyway.defaultSchema=auth
flyway.driver=org.postgresql.Driver
flyway.locations=classpath:db/migration/auth