flyway.url=jdbc:postgresql://testproj-flex-dev.postgres.database.azure.com:5432/postgres
flyway.password=24o62o!!
flyway.user=adm
flyway.schemas=auth
flyway.driver=org.postgresql.Driver
flyway.locations=classpath:db/migration/auth_migration