<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.testproj.db</groupId>
        <artifactId>db</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <groupId>net.testproj.db.schema</groupId>
    <artifactId>schema</artifactId>
    <build>
        <plugins>
            <plugin>
                <groupId>org.flywaydb</groupId>
                <artifactId>flyway-maven-plugin</artifactId>
                <version>10.15.0</version>
                <dependencies>
                    <dependency>
                        <groupId>org.postgresql</groupId>
                        <artifactId>postgresql</artifactId>
                        <version>42.7.3</version>
                    </dependency>
                    <dependency>
                        <groupId>org.flywaydb</groupId>
                        <artifactId>flyway-database-postgresql</artifactId>
                        <version>10.14.0</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>auth-migration</id>
                        <goals><goal>migrate</goal></goals>
                        <phase>generate-resources</phase>
                        <configuration>
                            <configFiles>
                                <configFile>${basedir}/flyway-auth.properties</configFile>
                            </configFiles>
                        </configuration>
                    </execution>
                    <execution>
                        <id>public-migration</id>
                        <goals><goal>migrate</goal></goals>
                        <phase>generate-resources</phase>
                        <configuration>
                            <configFiles>
                                <configFile>${basedir}/flyway-public.properties</configFile>
                            </configFiles>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <version>3.19.13</version>
                <dependencies>
                    <dependency>
                        <groupId>org.postgresql</groupId>
                        <artifactId>postgresql</artifactId>
                        <version>42.7.3</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <id>generate-public</id>
                        <goals><goal>generate</goal></goals>
                        <configuration>
                            <jdbc>
                                <driver>org.postgresql.Driver</driver>
                                <!--suppress UnresolvedMavenProperty -->
                                <url>${env.DB_URL}</url>
                                <!--suppress UnresolvedMavenProperty -->
                                <user>${env.DB_USER_NAME}</user>
                                <!--suppress UnresolvedMavenProperty -->
                                <password>${env.DB_PASSWORD}</password>
                                <driver>org.postgresql.Driver</driver>
                            </jdbc>
                            <generator>
                                <name>org.jooq.codegen.JavaGenerator</name>
                                <database>
                                    <name>org.jooq.meta.postgres.PostgresDatabase</name>
                                    <inputSchema>public</inputSchema>
                                </database>
                                <generate>
                                    <tables>true</tables>
                                </generate>
                                <target>
                                    <packageName>net.testproj.db.pb</packageName>
                                    <directory>src/main/java</directory>
                                </target>
                            </generator>
                        </configuration>
                    </execution>
                    <execution>
                        <phase>generate-sources</phase>
                        <id>generate-auth</id>
                        <goals><goal>generate</goal></goals>
                        <configuration>
                            <jdbc>
                                <driver>org.postgresql.Driver</driver>
                                <!--suppress UnresolvedMavenProperty -->
                                <url>${env.DB_URL}</url>
                                <!--suppress UnresolvedMavenProperty -->
                                <user>${env.DB_USER_NAME}</user>
                                <!--suppress UnresolvedMavenProperty -->
                                <password>${env.DB_PASSWORD}</password>
                                <driver>org.postgresql.Driver</driver>
                            </jdbc>
                            <generator>
                                <name>org.jooq.codegen.JavaGenerator</name>
                                <database>
                                    <name>org.jooq.meta.postgres.PostgresDatabase</name>
                                    <inputSchema>auth</inputSchema>
                                </database>
                                <generate>
                                    <tables>true</tables>
                                </generate>
                                <target>
                                    <packageName>net.testproj.db.auth</packageName>
                                    <directory>src/main/java</directory>
                                </target>
                            </generator>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>