<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com</groupId>
        <artifactId>db</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <groupId>com.db</groupId>
    <artifactId>schema</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-database-postgresql</artifactId>
            <version>10.14.0</version>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
            <version>10.15.2</version>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq-meta</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq-codegen</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.flywaydb</groupId>
                <artifactId>flyway-maven-plugin</artifactId>
                <version>10.15.0</version>
                <dependencies>
                    <dependency>
                        <groupId>org.postgresql</groupId>
                        <artifactId>postgresql</artifactId>
                        <version>42.7.3</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <configFiles>
                        <configFile>${basedir}/flyway.conf</configFile>
                    </configFiles>
                </configuration>
                <executions>
                    <execution>
                        <goals><goal>migrate</goal></goals>
                        <phase>generate-resources</phase>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <version>3.19.13</version>
                <executions>
                    <execution>
                        <id>generate</id>
                        <goals><goal>generate</goal></goals>
                        <configuration>
                            <jdbc>
                                <driver>org.postgresql.Driver</driver>
                                <url>jdbc:postgresql://auction4.postgres.database.azure.com:5432/postgres</url>
                                <user>adm</user>
                                <password>24o62o!!</password>
                            </jdbc>
                            <generator>
                                <name>org.jooq.codegen.DefaultGenerator</name>
                                <database>
                                    <name>org.jooq.meta.postgres.PostgresDatabase</name>
                                    <inputSchema>public</inputSchema>
                                    <inputCatalog/>
                                </database>
                                <generate>
                                    <daos>false</daos>
                                    <pojos>false</pojos>
                                    <indexes>true</indexes>
                                    <keys>true</keys>
                                    <links>false</links>
                                    <records>false</records>
                                    <routines>false</routines>
                                    <sequences>false</sequences>
                                    <tables>true</tables>
                                    <udts>false</udts>
                                    <sources>false</sources>
                                    <sourcesOnViews>false</sourcesOnViews>
                                    <queues>false</queues>
                                    <sequenceFlags>false</sequenceFlags>
                                </generate>
                                <target>
                                    <packageName>com.db.schema.generated</packageName>
                                    <directory>src/main/java</directory>
                                </target>
                            </generator>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
