/*
 * This file is generated by jOOQ.
 */
package net.testproj.db.pb;


import net.testproj.db.pb.tables.FlywaySchemaHistory;
import net.testproj.db.pb.tables.Products;
import net.testproj.db.pb.tables.Users;
import net.testproj.db.pb.tables.records.FlywaySchemaHistoryRecord;
import net.testproj.db.pb.tables.records.ProductsRecord;
import net.testproj.db.pb.tables.records.UsersRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<ProductsRecord> PRODUCTS_CATEGORIES_KEY = Internal.createUniqueKey(Products.PRODUCTS, DSL.name("products_categories_key"), new TableField[] { Products.PRODUCTS.CATEGORIES }, true);
    public static final UniqueKey<ProductsRecord> PRODUCTS_PKEY = Internal.createUniqueKey(Products.PRODUCTS, DSL.name("products_pkey"), new TableField[] { Products.PRODUCTS.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_AUTH_USER_ID_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_auth_user_id_key"), new TableField[] { Users.USERS.AUTH_USER_ID }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);
}
