/*
 * This file is generated by jOOQ.
 */
package net.testproj.db.auth.schema;


import java.util.Arrays;
import java.util.List;

import net.testproj.db.auth.schema.tables.AuthUsers;
import net.testproj.db.auth.schema.tables.EmailConfirmationTokens;
import net.testproj.db.auth.schema.tables.FlywaySchemaHistory;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Auth extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>auth</code>
     */
    public static final Auth AUTH = new Auth();

    /**
     * The table <code>auth.auth_users</code>.
     */
    public final AuthUsers AUTH_USERS = AuthUsers.AUTH_USERS;

    /**
     * The table <code>auth.email_confirmation_tokens</code>.
     */
    public final EmailConfirmationTokens EMAIL_CONFIRMATION_TOKENS = EmailConfirmationTokens.EMAIL_CONFIRMATION_TOKENS;

    /**
     * The table <code>auth.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * No further instances allowed
     */
    private Auth() {
        super("auth", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AuthUsers.AUTH_USERS,
            EmailConfirmationTokens.EMAIL_CONFIRMATION_TOKENS,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY
        );
    }
}
