/*
 * This file is generated by jOOQ.
 */
package net.testproj.db.auth.schema;


import net.testproj.db.auth.schema.tables.AuthUsers;
import net.testproj.db.auth.schema.tables.EmailConfirmationTokens;
import net.testproj.db.auth.schema.tables.FlywaySchemaHistory;
import net.testproj.db.auth.schema.tables.records.AuthUsersRecord;
import net.testproj.db.auth.schema.tables.records.EmailConfirmationTokensRecord;
import net.testproj.db.auth.schema.tables.records.FlywaySchemaHistoryRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * auth.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthUsersRecord> AUTH_USERS_PKEY = Internal.createUniqueKey(AuthUsers.AUTH_USERS, DSL.name("auth_users_pkey"), new TableField[] { AuthUsers.AUTH_USERS.ID }, true);
    public static final UniqueKey<EmailConfirmationTokensRecord> EMAIL_CONFIRMATION_TOKENS_PKEY = Internal.createUniqueKey(EmailConfirmationTokens.EMAIL_CONFIRMATION_TOKENS, DSL.name("email_confirmation_tokens_pkey"), new TableField[] { EmailConfirmationTokens.EMAIL_CONFIRMATION_TOKENS.ID }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
}
