/*
 * This file is generated by jOOQ.
 */
package net.testproj.db.auth.schema;


import net.testproj.db.auth.schema.tables.AuthUsers;
import net.testproj.db.auth.schema.tables.EmailConfirmationTokens;
import net.testproj.db.auth.schema.tables.FlywaySchemaHistory;


/**
 * Convenience access to all tables in auth.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>auth.auth_users</code>.
     */
    public static final AuthUsers AUTH_USERS = AuthUsers.AUTH_USERS;

    /**
     * The table <code>auth.email_confirmation_tokens</code>.
     */
    public static final EmailConfirmationTokens EMAIL_CONFIRMATION_TOKENS = EmailConfirmationTokens.EMAIL_CONFIRMATION_TOKENS;

    /**
     * The table <code>auth.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
