/*
 * This file is generated by jOOQ.
 */
package net.testproj.db.auth;


import net.testproj.db.auth.tables.FlywaySchemaHistory;


/**
 * Convenience access to all tables in auth.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>auth.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
