/*
 * This file is generated by jOOQ.
 */
package net.testproj.db.auth.schema.tables;


import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;

import net.testproj.db.auth.schema.Auth;
import net.testproj.db.auth.schema.Keys;
import net.testproj.db.auth.schema.tables.records.AuthUsersRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuthUsers extends TableImpl<AuthUsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>auth.auth_users</code>
     */
    public static final AuthUsers AUTH_USERS = new AuthUsers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthUsersRecord> getRecordType() {
        return AuthUsersRecord.class;
    }

    /**
     * The column <code>auth.auth_users.id</code>.
     */
    public final TableField<AuthUsersRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>auth.auth_users.created</code>.
     */
    public final TableField<AuthUsersRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>auth.auth_users.updated</code>.
     */
    public final TableField<AuthUsersRecord, LocalDateTime> UPDATED = createField(DSL.name("updated"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>auth.auth_users.disabled</code>.
     */
    public final TableField<AuthUsersRecord, Boolean> DISABLED = createField(DSL.name("disabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>auth.auth_users.activated</code>.
     */
    public final TableField<AuthUsersRecord, Boolean> ACTIVATED = createField(DSL.name("activated"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>auth.auth_users.role</code>.
     */
    public final TableField<AuthUsersRecord, Integer> ROLE = createField(DSL.name("role"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>auth.auth_users.login</code>.
     */
    public final TableField<AuthUsersRecord, String> LOGIN = createField(DSL.name("login"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>auth.auth_users.password</code>.
     */
    public final TableField<AuthUsersRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>auth.auth_users.email</code>.
     */
    public final TableField<AuthUsersRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255), this, "");

    private AuthUsers(Name alias, Table<AuthUsersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AuthUsers(Name alias, Table<AuthUsersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>auth.auth_users</code> table reference
     */
    public AuthUsers(String alias) {
        this(DSL.name(alias), AUTH_USERS);
    }

    /**
     * Create an aliased <code>auth.auth_users</code> table reference
     */
    public AuthUsers(Name alias) {
        this(alias, AUTH_USERS);
    }

    /**
     * Create a <code>auth.auth_users</code> table reference
     */
    public AuthUsers() {
        this(DSL.name("auth_users"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Auth.AUTH;
    }

    @Override
    public UniqueKey<AuthUsersRecord> getPrimaryKey() {
        return Keys.AUTH_USERS_PKEY;
    }

    @Override
    public AuthUsers as(String alias) {
        return new AuthUsers(DSL.name(alias), this);
    }

    @Override
    public AuthUsers as(Name alias) {
        return new AuthUsers(alias, this);
    }

    @Override
    public AuthUsers as(Table<?> alias) {
        return new AuthUsers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUsers rename(String name) {
        return new AuthUsers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUsers rename(Name name) {
        return new AuthUsers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUsers rename(Table<?> name) {
        return new AuthUsers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUsers where(Condition condition) {
        return new AuthUsers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUsers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUsers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUsers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthUsers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthUsers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthUsers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthUsers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUsers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUsers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
