/*
 * This file is generated by jOOQ.
 */
package net.testproj.db.auth.schema.tables;


import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;

import net.testproj.db.auth.schema.Auth;
import net.testproj.db.auth.schema.Keys;
import net.testproj.db.auth.schema.enums.ConfirmationTokenStatus;
import net.testproj.db.auth.schema.tables.records.EmailConfirmationTokensRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmailConfirmationTokens extends TableImpl<EmailConfirmationTokensRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>auth.email_confirmation_tokens</code>
     */
    public static final EmailConfirmationTokens EMAIL_CONFIRMATION_TOKENS = new EmailConfirmationTokens();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmailConfirmationTokensRecord> getRecordType() {
        return EmailConfirmationTokensRecord.class;
    }

    /**
     * The column <code>auth.email_confirmation_tokens.id</code>.
     */
    public final TableField<EmailConfirmationTokensRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>auth.email_confirmation_tokens.user_id</code>.
     */
    public final TableField<EmailConfirmationTokensRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>auth.email_confirmation_tokens.token</code>.
     */
    public final TableField<EmailConfirmationTokensRecord, UUID> TOKEN = createField(DSL.name("token"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>auth.email_confirmation_tokens.created_at</code>.
     */
    public final TableField<EmailConfirmationTokensRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>auth.email_confirmation_tokens.expires_at</code>.
     */
    public final TableField<EmailConfirmationTokensRecord, LocalDateTime> EXPIRES_AT = createField(DSL.name("expires_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>auth.email_confirmation_tokens.status</code>.
     */
    public final TableField<EmailConfirmationTokensRecord, ConfirmationTokenStatus> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR.defaultValue(DSL.field(DSL.raw("'PENDING'::confirmation_token_status"), SQLDataType.VARCHAR)).asEnumDataType(ConfirmationTokenStatus.class), this, "");

    private EmailConfirmationTokens(Name alias, Table<EmailConfirmationTokensRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EmailConfirmationTokens(Name alias, Table<EmailConfirmationTokensRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>auth.email_confirmation_tokens</code> table
     * reference
     */
    public EmailConfirmationTokens(String alias) {
        this(DSL.name(alias), EMAIL_CONFIRMATION_TOKENS);
    }

    /**
     * Create an aliased <code>auth.email_confirmation_tokens</code> table
     * reference
     */
    public EmailConfirmationTokens(Name alias) {
        this(alias, EMAIL_CONFIRMATION_TOKENS);
    }

    /**
     * Create a <code>auth.email_confirmation_tokens</code> table reference
     */
    public EmailConfirmationTokens() {
        this(DSL.name("email_confirmation_tokens"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Auth.AUTH;
    }

    @Override
    public UniqueKey<EmailConfirmationTokensRecord> getPrimaryKey() {
        return Keys.EMAIL_CONFIRMATION_TOKENS_PKEY;
    }

    @Override
    public EmailConfirmationTokens as(String alias) {
        return new EmailConfirmationTokens(DSL.name(alias), this);
    }

    @Override
    public EmailConfirmationTokens as(Name alias) {
        return new EmailConfirmationTokens(alias, this);
    }

    @Override
    public EmailConfirmationTokens as(Table<?> alias) {
        return new EmailConfirmationTokens(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailConfirmationTokens rename(String name) {
        return new EmailConfirmationTokens(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailConfirmationTokens rename(Name name) {
        return new EmailConfirmationTokens(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailConfirmationTokens rename(Table<?> name) {
        return new EmailConfirmationTokens(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailConfirmationTokens where(Condition condition) {
        return new EmailConfirmationTokens(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailConfirmationTokens where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailConfirmationTokens where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailConfirmationTokens where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmailConfirmationTokens where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmailConfirmationTokens where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmailConfirmationTokens where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmailConfirmationTokens where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailConfirmationTokens whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailConfirmationTokens whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
