# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - testproj-api

on:
  push:
    branches:
      - dev-1.x.x
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USER_NAME: ${{ secrets.DB_USER_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install

      - name: List api target
        run: ls -la api/target

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/api/target/api-0.0.1-SNAPSHOT-exec.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EF7F602D80FC403A90788F151858FD75 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D4D27986EB724B779BC7913ADA7D052C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A0235E59601D498CB447D637F3599544 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'testproj-api'
          slot-name: 'Production'
          package: 'api-0.0.1-SNAPSHOT-exec.jar'
          